### PR TITLE
Remove SpaceDamage metadata

### PR DESCRIPTION
**Pull request by Lemonymous**
The data that was previously available via SpaceDamage:GetMetadata() is now available via new functions added to SpaceDamage objects when memedit is enabled:

### SpaceDamage
- GetAnimState
- GetGrappleAnim
- GetGrappleTarget
- GetMoveType
- SetAnimState
- SetGrappleAnim
- SetGrappleTarget
- SetMoveType

### CODE REVIEW

**Comment by Lemonymous** [comment]
Addresses #197 and #198

**Comment by KnightMiner** [comment]
Just to be clear, did we decide on removing these functions instead of having them return false/empty table? If so, looks fine to me.

**Comment by Lemonymous** [comment]
I didn't feel we got 100% clarity on that, no.

I first attempted to go though the functions and have them exist, but be "inert" and return values that made sense, but it wasn't easy in every case, so I just did this instead.

I think this might actually make it easier for future maintainers, by removing what would essentially be inert dead code.

I added it as a PR though, so that we can have this discussion here. I am open to doing it differently as well.

**Comment by KnightMiner** [comment]
I don't personally use the functions so I have no preference either way. I think its just tosx who mentioned using it, so just a question of whether they would rather update to not call them or keep things working.

**Comment by Lemonymous** [comment]
One option could be to add the functions back in the compat file

**Pull request merged**
